### ISSUE TITLE
Clarify how "Active..." works (was: Set Load not working)

### ISSUE THREAD

**Issue by sanjaysrikumar** [dss-extensions/dss-extensions#12]
### Versions

- [ ] Python version: 3.7.4
- [ ] Python architecture: x64
- [ ] Operating system and version: Windows 10 Enterprise
- [ ] OpenDSSDirect.py version number:  v0.40

Hello all, 

I am fairly a beginner to using this package as well as python. I have an OpenDSS circuit that i want to run by setting the load values for a few loads before proceeding to "Run" the simulation. 

My understanding is that using the `opendssdirect.Loads.Name(*args)` command will set the load "Active" 
and *args is the string name of my load in OpenDSS i.e. 'L1' from this piece of code in OpenDSS (new Load.L1 bus=B1814.1.2 Phases=1 kV=0.240 kW=1 kvar=0.484)

once i have set the specific load active, i use the following command to set a new value for its kW and kVar 
```
opendssdirect.Loads.Names('L1')
opendssdirect.Loads.kW=0.604
opendssdirect.Loads.kvar=0.311
```

This approach has not really worked for me and i also tried the approach of using opendssdirect.Loads.Idx() and i was not successful. 

Is this the right steps that i should be taking in order to change the load values ?

**Comment by PMeira** [comment]
A more complete exploration of this topic is available on https://dss-extensions.org/classic_api#the-active-paradigm

Since we have a working alternative (in Python at first), also mentioned in the link, we can finally close this.
