### ISSUE TITLE
Create Rust bindings

### ISSUE THREAD

**Issue by PMeira** [dss-extensions/dss-extensions#34]
Use [rust-bindgen](https://rust-lang.github.io/rust-bindgen/) to generate part of the boilerplate code from our DSS C-API headers. Some initial discussion and sample code in https://github.com/dss-extensions/dss_capi/issues/125#issuecomment-1828580418

It will require [num-complex](https://github.com/rust-num/num-complex) crate for complex numbers. Curiously, Rust is the only language so far that doesn't include native support complex numbers (quite a letdown, IMO).

After the basic stuff is done, we can add something like [ndarray](https://docs.rs/ndarray/latest/ndarray/) to properly expose the matrices, and a proper container for sparse matrices. There are multiple Rust implementations for sparse matrices, we need to check quick one is better for our use-case (we don't need sparse solvers, just the matrix).

As a final step, a "port" of AltDSS-Python, exposing the new Obj and Alt APIs, should complete the package.

For the classic API, we may try to use the (WIP, not public) DSS C-API wrapper for the new official OpenDSSDirect.DLL. Although it doesn't implement the equivalent of all API functions, it should allow most of the basic features.

An empty repo is already created at https://github.com/dss-extensions/AltDSS-Rust  
We should create issues there for tracking features beyond the basic/classic OpenDSS API.

**Comment by keegit** [comment]
Hey @PMeira we've actually decided to release our Rust bindings and wrapper crate. Would we need to use a specific license in order to get our Rust crates into the dss-extensions organization? We already have a lot of code for it and would be happy to release/help get it 'officially' into the extensions eco-system.

**Comment by PMeira** [comment]
Nice! I'm away till Monday, but about licenses I think we use (variations of) BSD or MIT, but LGPL is OK too since KLU (used by OpenDSS) is LGPL already. Feel free to propose alternatives though.

I have an initial draft to push when I'm back, but haven't tested it much. We can merge it from/to yours and work from there.

(pinging @dss-extensions if anyone has input)

**Comment by keegit** [comment]
@PMeira Is an apache 2 license acceptable? That seems to be what we would prefer to release under. Assuming it is, I'll go ahead and license our source code and then share the public repository once we release it.

**Comment by PMeira** [comment]
@keegit Yes, I think Apache 2 is fine. If, down the line, we reimplement the whole engine in Rust, that could be a separate package or something like that, with a BSD license to match OpenDSS.

I pushed my code now, with some examples. I left some notes in the [README there](https://github.com/dss-extensions/AltDSS-Rust), please check those first. Besides that, one ugly thing to adjust would be to avoid transmute on the enums. but that's safe if we ensure the engine enums always match the Rust enums.

From your repos, after a quick browsing, I can see some things like:
- The build process in `dss_rs_sys` could be ported as a whole since I completely ignored that, as well as the CI, testing and other scripts from `dss_rs` :smile: 
- Since I wanted to enable multi-threading as soon as possible (already works), I used structs instead of modules, but the basics seem similar. Besides the error handling, one thing of note is that I generally used boxed slices -- this would be easy to change if vectors are preferred.
- I noticed you already implemented some of the extra storage functions, for example, so we can port that too.
- Currently I kept a single file per module, but probably separating that into multiple files is better if we intend to manually change a lot. My preference would be to kinda freeze the "classic" module after the initial adjustments, and move on to implement the new API functions for everything.
- There's the whole naming convention thing as I wrote in the README that I'm not sure how to handle yet.
- I had the advantage that I'm using the latest beta and the C headers were updated to include some more consts. This made the output from bindgen a bit better.

I can take a better look later, but also feel free to point anything specific. If you think it's worth to schedule a meeting, drop me an email so we can arrange it.

After this initial work is done, the next step would be to expose all objects as in [dss.hpp](https://github.com/dss-extensions/dss_capi/blob/master/include/dss_obj.hpp) and (Alt)DSS-Python, like in https://github.com/dss-extensions/dss_python/blob/0.15.0b1/dss/altdss/Storage.py -- this is a mix of some generalized code from the classic API + generated code from the AltDSS-Schema outputs; a main aspect is that all DSS object and bus pointers have lifetimes bound to the circuit and some circuit events, so we need to check how to best track that in Rust.

Later on, after the engine's plug-in system is ready, reimplementing/replacing parts of the engine and complementing with Rust versions would be a good step (I mentioned that to @kdheepak a while ago). There is no current plan to port the whole engine to Rust, but we can probably ponder that in 2025. Currently, both us and EPRI have C++ versions in progress, which will already make integrating with Rust easier.

**Comment by keegit** [comment]
Alright, this is really cool and exciting! Initial emotions aside, here are my thoughts:

- I'm assuming your Rust crate _doesn't_  have the memory leaks ours does. In which case I would love to get our CI/tests/tooling ported into your Rust crate. The memory leak is our biggest priority right now, so once we've added CI/tooling/testing to your Rust crate I plan to swap the API we use (OES one) with the new one (AltDSS-Rust).

- I would be fine with avoiding use of snake case (even though it's Rust convention) to make porting/using the API much easier. That being said we'll need to add lint hints to avoid compiler warnings.

- Biggest hurdle with getting it on crates.io is going to be handling the dependency builds (C API/klusolve/eigen/suitesparse), but that's probably not a huge priority right now.

- Boxed slices vs. Vectors: I think using boxed slices is a better idea due to reduced overhead. 

- Yeah, I'll drop you an email to schedule a meeting with some times, but if none of those work feel free to propose a different time.

**Comment by PMeira** [comment]
> The memory leak is our biggest priority right now

Just pushed a commit to fix an issue to arrays of strings. With that, no leaks from some basic tests and the examples. There might be some leaks in DSS C-API, but a lot of leaks have been handled in previous releases.

It's a good idea to prepare some long running tests (with a variety of sample circuits) to check internal leaks. Significant leaks becomes very prominent for those. OpenDSS has tens of components and options that are barely used by us or the community in general, so there might be some issues lurking there.

> I would be fine with avoiding use of snake case (even though it's Rust convention) to make porting/using the API much easier. That being said we'll need to add lint hints to avoid compiler warnings.

I added some already, but that can be tweaked to be more specific. And there are a few places, like some of the code in `common.rs`, that can be freely adjusted.

Remember I'm not proficient in Rust, there could be some weird code here and there.

**Comment by PMeira** [comment]
Just closing this since the new repo is active. Everyone is welcome at https://github.com/dss-extensions/AltDSS-Rust
